CREATE TABLE tb_user_auth (
                              id bigint generated by default as identity,
                              username text not null,
                              password text not null,

                              primary key (id)
);

COMMENT ON TABLE tb_user_auth is 'Table with the users of the system';
COMMENT ON COLUMN tb_user_auth.id is 'Id of the user';
COMMENT ON COLUMN tb_user_auth.username is 'User name of the user';
COMMENT ON COLUMN tb_user_auth.password is 'Password of the user';