spring:
  application:
    name: study-gateway
  # Configuration of the gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

# Configure the port of the gateway
server:
  port: 8083
# Configure the eureka server:
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka