CREATE TABLE tb_auth_user (
                              id BIGINT GENERATED BY DEFAULT as identity,
                              username varchar(100) not null,
                              password text not null,
                              first_name varchar(250) not null,
                              last_name varchar(250) not null,
                              email varchar(250),
                              is_active boolean not null,
                              is_staff boolean not null,
                              is_admin boolean not null,

                              primary key (id)
);

COMMENT ON table tb_auth_user is 'This table has all the users of the system';
COMMENT ON column tb_auth_user.username is 'username of the user';
COMMENT ON column tb_auth_user.password is 'Password of the user';
COMMENT ON column tb_auth_user.first_name is 'First name of the user';
comment on column tb_auth_user.last_name is 'Last name of the user';
comment on column tb_auth_user.email is 'Email of the user';
comment on column tb_auth_user.is_active is 'Tells if the user still active on the system';
comment on column tb_auth_user.is_staff is 'Tells if the user is staff of the business';
comment on column tb_auth_user.is_admin is 'Tells if the user has admin privilegies';